var annotated_dup =
[
    [ "SRDatalog", "d5/dd6/namespace_s_r_datalog.html", [
      [ "AST", "db/dde/namespace_s_r_datalog_1_1_a_s_t.html", [
        [ "mir", "d5/d2a/namespace_s_r_datalog_1_1_a_s_t_1_1mir.html", [
          [ "is_bound_vars", "dc/dde/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1is__bound__vars.html", null ],
          [ "is_bound_vars&lt; BoundVars&lt; Vars... &gt; &gt;", "dc/d61/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1is__bound__vars_3_01_bound_vars_3_01_vars_8_8_8_01_4_01_4.html", null ],
          [ "ColumnSource", "d4/dea/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1_column_source.html", null ],
          [ "ColumnJoin", "d3/d92/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1_column_join.html", null ],
          [ "DestinationRelation", "da/dd1/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1_destination_relation.html", null ]
        ] ],
        [ "TStringToStringImpl&lt; TString&lt; chars... &gt; &gt;", "d3/d27/struct_s_r_datalog_1_1_a_s_t_1_1_t_string_to_string_impl_3_01_t_string_3_01chars_8_8_8_01_4_01_4.html", null ],
        [ "RelationSchema", "d0/d70/struct_s_r_datalog_1_1_a_s_t_1_1_relation_schema.html", "d0/d70/struct_s_r_datalog_1_1_a_s_t_1_1_relation_schema" ],
        [ "Var", "dc/dd9/struct_s_r_datalog_1_1_a_s_t_1_1_var.html", "dc/dd9/struct_s_r_datalog_1_1_a_s_t_1_1_var" ],
        [ "CppExpr", "d6/d11/struct_s_r_datalog_1_1_a_s_t_1_1_cpp_expr.html", "d6/d11/struct_s_r_datalog_1_1_a_s_t_1_1_cpp_expr" ],
        [ "Const", "db/d28/struct_s_r_datalog_1_1_a_s_t_1_1_const.html", null ],
        [ "is_cpp_expr", "db/d4b/struct_s_r_datalog_1_1_a_s_t_1_1is__cpp__expr.html", null ],
        [ "is_cpp_expr&lt; CppExpr&lt; std::tuple&lt; Vars... &gt;, Func &gt; &gt;", "d4/de8/struct_s_r_datalog_1_1_a_s_t_1_1is__cpp__expr_3_01_cpp_expr_3_01std_1_1tuple_3_01_vars_8_8_8_01_4_00_01_func_01_4_01_4.html", null ],
        [ "ArityMismatchError", "d1/d3d/struct_s_r_datalog_1_1_a_s_t_1_1_arity_mismatch_error.html", null ],
        [ "Clause", "d4/dbf/struct_s_r_datalog_1_1_a_s_t_1_1_clause.html", null ],
        [ "LetClause", "d9/d11/struct_s_r_datalog_1_1_a_s_t_1_1_let_clause.html", null ],
        [ "JoinPlan", "d4/d58/struct_s_r_datalog_1_1_a_s_t_1_1_join_plan.html", "d4/d58/struct_s_r_datalog_1_1_a_s_t_1_1_join_plan" ],
        [ "FixpointToMp11List&lt; Fixpoint&lt; Rules... &gt; &gt;", "df/d00/struct_s_r_datalog_1_1_a_s_t_1_1_fixpoint_to_mp11_list_3_01_fixpoint_3_01_rules_8_8_8_01_4_01_4.html", "df/d00/struct_s_r_datalog_1_1_a_s_t_1_1_fixpoint_to_mp11_list_3_01_fixpoint_3_01_rules_8_8_8_01_4_01_4" ],
        [ "GetRulesFromFixpoint", "d6/d31/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_fixpoint.html", null ],
        [ "GetRulesFromFixpoint&lt; Fixpoint&lt; Rules... &gt; &gt;", "d7/df4/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_fixpoint_3_01_fixpoint_3_01_rules_8_8_8_01_4_01_4.html", "d7/df4/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_fixpoint_3_01_fixpoint_3_01_rules_8_8_8_01_4_01_4" ],
        [ "NonIterativeRuleSets", "dd/dbc/struct_s_r_datalog_1_1_a_s_t_1_1_non_iterative_rule_sets.html", null ],
        [ "GetRulesFromNonIterativeRuleSets&lt; NonIterativeRuleSets&lt; Rules... &gt; &gt;", "d4/db4/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_non_iterative_rule_sets_3_01_non_iterative_rule_sets_3_01_rules_8_8_8_01_4_01_4.html", "d4/db4/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_non_iterative_rule_sets_3_01_non_iterative_rule_sets_3_01_rules_8_8_8_01_4_01_4" ],
        [ "is_database", "d4/d8a/struct_s_r_datalog_1_1_a_s_t_1_1is__database.html", null ],
        [ "is_database&lt; Database&lt; Schemas... &gt; &gt;", "db/db2/struct_s_r_datalog_1_1_a_s_t_1_1is__database_3_01_database_3_01_schemas_8_8_8_01_4_01_4.html", null ],
        [ "Program", "de/dd6/struct_s_r_datalog_1_1_a_s_t_1_1_program.html", "de/dd6/struct_s_r_datalog_1_1_a_s_t_1_1_program" ],
        [ "DatabaseToRelationTypes&lt; Database&lt; Schemas... &gt; &gt;", "d5/d73/struct_s_r_datalog_1_1_a_s_t_1_1_database_to_relation_types_3_01_database_3_01_schemas_8_8_8_01_4_01_4.html", "d5/d73/struct_s_r_datalog_1_1_a_s_t_1_1_database_to_relation_types_3_01_database_3_01_schemas_8_8_8_01_4_01_4" ],
        [ "InitDatabaseHelper", "d8/dfd/struct_s_r_datalog_1_1_a_s_t_1_1_init_database_helper.html", null ],
        [ "InitDatabaseHelper&lt; Database&lt; Schemas... &gt; &gt;", "d8/dd2/struct_s_r_datalog_1_1_a_s_t_1_1_init_database_helper_3_01_database_3_01_schemas_8_8_8_01_4_01_4.html", null ],
        [ "GetVarsFromTerm", "d3/deb/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term.html", null ],
        [ "GetVarsFromTerm&lt; V &gt;", "d0/d5e/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term_3_01_v_01_4.html", "d0/d5e/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term_3_01_v_01_4" ],
        [ "GetVarsFromTerm&lt; C &gt;", "df/d9f/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term_3_01_c_01_4.html", "df/d9f/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term_3_01_c_01_4" ],
        [ "GetVarsFromTerm&lt; CppExpr&lt; CVars, F &gt; &gt;", "d2/d87/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term_3_01_cpp_expr_3_01_c_vars_00_01_f_01_4_01_4.html", "d2/d87/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term_3_01_cpp_expr_3_01_c_vars_00_01_f_01_4_01_4" ],
        [ "GetVarsFromTerms", "dd/d28/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_terms.html", "dd/d28/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_terms" ],
        [ "GetNormalClauseTerms", "d0/de5/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_terms.html", null ],
        [ "GetNormalClauseTerms&lt; Clause&lt; S, Ver, Vars... &gt; &gt;", "df/d69/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_terms_3_01_clause_3_01_s_00_01_ver_00_01_vars_8_8_8_01_4_01_4.html", "df/d69/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_terms_3_01_clause_3_01_s_00_01_ver_00_01_vars_8_8_8_01_4_01_4" ],
        [ "GetNormalClauseSchema", "da/dae/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_schema.html", null ],
        [ "GetNormalClauseSchema&lt; Clause&lt; S, Ver, Vars... &gt; &gt;", "d0/d48/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_schema_3_01_clause_3_01_s_00_01_ver_00_01_vars_8_8_8_01_4_01_4.html", "d0/d48/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_schema_3_01_clause_3_01_s_00_01_ver_00_01_vars_8_8_8_01_4_01_4" ],
        [ "GetNormalClauseVersion", "d0/d54/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_version.html", null ],
        [ "GetNormalClauseVersion&lt; Clause&lt; S, Ver, Vars... &gt; &gt;", "d8/d4b/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_version_3_01_clause_3_01_s_00_01_ver_00_01_vars_8_8_8_01_4_01_4.html", null ],
        [ "GetLetClauseVars", "d4/d47/struct_s_r_datalog_1_1_a_s_t_1_1_get_let_clause_vars.html", null ],
        [ "GetLetClauseVars&lt; LetClause&lt; V, CppExpr&lt; CVars, F &gt; &gt; &gt;", "df/dbb/struct_s_r_datalog_1_1_a_s_t_1_1_get_let_clause_vars_3_01_let_clause_3_01_v_00_01_cpp_expr_3_01_c_vars_00_01_f_01_4_01_4_01_4.html", "df/dbb/struct_s_r_datalog_1_1_a_s_t_1_1_get_let_clause_vars_3_01_let_clause_3_01_v_00_01_cpp_expr_3_01_c_vars_00_01_f_01_4_01_4_01_4" ],
        [ "GetClauseVars", "da/dea/struct_s_r_datalog_1_1_a_s_t_1_1_get_clause_vars.html", null ],
        [ "GetClauseVars&lt; C &gt;", "dd/dc6/struct_s_r_datalog_1_1_a_s_t_1_1_get_clause_vars_3_01_c_01_4.html", "dd/dc6/struct_s_r_datalog_1_1_a_s_t_1_1_get_clause_vars_3_01_c_01_4" ],
        [ "GetExprDependencies", "d5/dcd/struct_s_r_datalog_1_1_a_s_t_1_1_get_expr_dependencies.html", null ],
        [ "GetExprDependencies&lt; CppExpr&lt; CapturedVars, Func &gt; &gt;", "db/da6/struct_s_r_datalog_1_1_a_s_t_1_1_get_expr_dependencies_3_01_cpp_expr_3_01_captured_vars_00_01_func_01_4_01_4.html", "db/da6/struct_s_r_datalog_1_1_a_s_t_1_1_get_expr_dependencies_3_01_cpp_expr_3_01_captured_vars_00_01_func_01_4_01_4" ],
        [ "FindTermIndex", "dc/db4/struct_s_r_datalog_1_1_a_s_t_1_1_find_term_index.html", null ],
        [ "MapVarsToColumnIndexes", "d1/d47/struct_s_r_datalog_1_1_a_s_t_1_1_map_vars_to_column_indexes.html", "d1/d47/struct_s_r_datalog_1_1_a_s_t_1_1_map_vars_to_column_indexes" ],
        [ "GetRulesFromQuery", "d9/d56/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_query.html", null ],
        [ "GetRulesFromQuery&lt; Fixpoint&lt; Rules... &gt; &gt;", "d4/d7b/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_query_3_01_fixpoint_3_01_rules_8_8_8_01_4_01_4.html", "d4/d7b/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_query_3_01_fixpoint_3_01_rules_8_8_8_01_4_01_4" ],
        [ "GetRulesFromQuery&lt; NonIterativeRuleSets&lt; Rules... &gt; &gt;", "df/da3/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_query_3_01_non_iterative_rule_sets_3_01_rules_8_8_8_01_4_01_4.html", "df/da3/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_query_3_01_non_iterative_rule_sets_3_01_rules_8_8_8_01_4_01_4" ],
        [ "GetAllRulesFromQueries", "d6/d4d/struct_s_r_datalog_1_1_a_s_t_1_1_get_all_rules_from_queries.html", "d6/d4d/struct_s_r_datalog_1_1_a_s_t_1_1_get_all_rules_from_queries" ],
        [ "IndexSpecT", "d3/d0c/struct_s_r_datalog_1_1_a_s_t_1_1_index_spec_t.html", "d3/d0c/struct_s_r_datalog_1_1_a_s_t_1_1_index_spec_t" ],
        [ "SemiNaiveDatabase", "d2/d05/struct_s_r_datalog_1_1_a_s_t_1_1_semi_naive_database.html", "d2/d05/struct_s_r_datalog_1_1_a_s_t_1_1_semi_naive_database" ]
      ] ],
      [ "detail", "d8/d73/namespace_s_r_datalog_1_1detail.html", [
        [ "IndexRelInDBRels", "dd/d2a/struct_s_r_datalog_1_1detail_1_1_index_rel_in_d_b_rels.html", null ],
        [ "is_relation_ref", "df/d0f/struct_s_r_datalog_1_1detail_1_1is__relation__ref.html", null ],
        [ "is_relation_ref&lt; Relation&lt; SR, Attrs... &gt; &amp; &gt;", "d8/d08/struct_s_r_datalog_1_1detail_1_1is__relation__ref_3_01_relation_3_01_s_r_00_01_attrs_8_8_8_01_4_01_6_01_4.html", null ],
        [ "BuildIndexHelper", "dd/dfb/struct_s_r_datalog_1_1detail_1_1_build_index_helper.html", "dd/dfb/struct_s_r_datalog_1_1detail_1_1_build_index_helper" ],
        [ "BuildAllIndices_Impl", "d9/d55/struct_s_r_datalog_1_1detail_1_1_build_all_indices___impl.html", null ],
        [ "GetValueFromState", "d0/d27/struct_s_r_datalog_1_1detail_1_1_get_value_from_state.html", null ],
        [ "GetPrefixValues", "d3/d45/struct_s_r_datalog_1_1detail_1_1_get_prefix_values.html", null ],
        [ "GetPrefixValues&lt; mir::BoundVars&lt; Vars... &gt;, StateMap &gt;", "da/df8/struct_s_r_datalog_1_1detail_1_1_get_prefix_values_3_01mir_1_1_bound_vars_3_01_vars_8_8_8_01_4_00_01_state_map_01_4.html", null ],
        [ "GetPayloadValues", "df/d8a/struct_s_r_datalog_1_1detail_1_1_get_payload_values.html", null ],
        [ "GetPayloadValues&lt; std::tuple&lt; Terms... &gt;, StateMap &gt;", "d5/d61/struct_s_r_datalog_1_1detail_1_1_get_payload_values_3_01std_1_1tuple_3_01_terms_8_8_8_01_4_00_01_state_map_01_4.html", null ],
        [ "GetPayloadValues&lt; std::tuple&lt;&gt;, StateMap &gt;", "df/ddd/struct_s_r_datalog_1_1detail_1_1_get_payload_values_3_01std_1_1tuple_3_4_00_01_state_map_01_4.html", null ],
        [ "GenerateIterator", "d8/de1/struct_s_r_datalog_1_1detail_1_1_generate_iterator.html", null ],
        [ "GenerateIterator&lt; mir::ColumnSource&lt; IndexSpecT&lt; Schema, std::integer_sequence&lt; int, Cols... &gt;, Ver &gt;, PrefixVars &gt;, DB, StateMap &gt;", "d2/d4d/struct_s_r_datalog_1_1detail_1_1_generate_iterator_3_01mir_1_1_column_source_3_01_index_spec_t_31a7820df72adc7a13bc39cb3e44262da.html", null ],
        [ "MIRExecutor", "dc/d68/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor.html", null ],
        [ "MIRExecutor&lt; std::tuple&lt;&gt;, StateMap &gt;", "d4/dab/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor_3_01std_1_1tuple_3_4_00_01_state_map_01_4.html", null ],
        [ "MIRExecutor&lt; std::tuple&lt; HeadOp, TailOps... &gt;, StateMap &gt;", "dd/d3e/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor_3_01std_1_1tuple_3_01_head_op_00_01_tail_ops_8_8_8_01_4_00_01_state_map_01_4.html", null ],
        [ "MIRExecutor&lt; std::tuple&lt; mir::ColumnJoin&lt; VarToBind, Sources &gt;, TailOps... &gt;, StateMap &gt;", "d4/d88/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor_3_01std_1_1tuple_3_01mir_1_1_column_join_3_01_vaccde6c0ac674a2e9c46fbf1bf30fc0ee.html", null ],
        [ "MIRExecutor&lt; std::tuple&lt; LetClause&lt; VarToBind, CppExpr&lt; CapturedVars, Func &gt; &gt;, TailOps... &gt;, StateMap &gt;", "d1/d9e/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor_3_01std_1_1tuple_3_01_let_clause_3_01_var_to_bin8907e8d68030a7c70648f497f908557e.html", null ],
        [ "MIRExecutor&lt; std::tuple&lt; mir::DestinationRelation&lt; Schema, Terms, Ver &gt;, TailOps... &gt;, StateMap &gt;", "d9/d4e/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor_3_01std_1_1tuple_3_01mir_1_1_destination_relatiod77068713e8e97a230041d4e4f85930c.html", null ]
      ] ],
      [ "Column", "d3/d99/class_s_r_datalog_1_1_column.html", "d3/d99/class_s_r_datalog_1_1_column" ],
      [ "to_fn", "d1/d8b/struct_s_r_datalog_1_1to__fn.html", "d1/d8b/struct_s_r_datalog_1_1to__fn" ],
      [ "to_impl", "dc/d97/struct_s_r_datalog_1_1to__impl.html", "dc/d97/struct_s_r_datalog_1_1to__impl" ],
      [ "GetIndexForClause", "d7/d48/struct_s_r_datalog_1_1_get_index_for_clause.html", "d7/d48/struct_s_r_datalog_1_1_get_index_for_clause" ],
      [ "MapClausesToSpecs_Impl", "d0/d7f/struct_s_r_datalog_1_1_map_clauses_to_specs___impl.html", "d0/d7f/struct_s_r_datalog_1_1_map_clauses_to_specs___impl" ],
      [ "ComputeNaiveIndices", "d3/dd6/struct_s_r_datalog_1_1_compute_naive_indices.html", null ],
      [ "ComputeNaiveIndices&lt; Rule&lt; Head, Body, JoinPlan &gt; &gt;", "d0/dad/struct_s_r_datalog_1_1_compute_naive_indices_3_01_rule_3_01_head_00_01_body_00_01_join_plan_01_4_01_4.html", "d0/dad/struct_s_r_datalog_1_1_compute_naive_indices_3_01_rule_3_01_head_00_01_body_00_01_join_plan_01_4_01_4" ],
      [ "ComputeIndicesForRules", "df/d67/struct_s_r_datalog_1_1_compute_indices_for_rules.html", "df/d67/struct_s_r_datalog_1_1_compute_indices_for_rules" ],
      [ "AllIndicesFromProgram", "dd/d24/struct_s_r_datalog_1_1_all_indices_from_program.html", "dd/d24/struct_s_r_datalog_1_1_all_indices_from_program" ],
      [ "is_let_clause_for_var_impl", "d5/da4/struct_s_r_datalog_1_1is__let__clause__for__var__impl.html", null ],
      [ "is_let_clause_for_var_impl&lt; Var, LetClause&lt; Var, Expr &gt; &gt;", "d4/df1/struct_s_r_datalog_1_1is__let__clause__for__var__impl_3_01_var_00_01_let_clause_3_01_var_00_01_expr_01_4_01_4.html", null ],
      [ "FindLetClauses", "d1/d9a/struct_s_r_datalog_1_1_find_let_clauses.html", "d1/d9a/struct_s_r_datalog_1_1_find_let_clauses" ],
      [ "FindNormalClausesWithVar", "de/d67/struct_s_r_datalog_1_1_find_normal_clauses_with_var.html", "de/d67/struct_s_r_datalog_1_1_find_normal_clauses_with_var" ],
      [ "ClauseToColumnSource_impl", "d5/d7b/struct_s_r_datalog_1_1_clause_to_column_source__impl.html", "d5/d7b/struct_s_r_datalog_1_1_clause_to_column_source__impl" ],
      [ "MapClausesToColumnSources", "d9/d8f/struct_s_r_datalog_1_1_map_clauses_to_column_sources.html", "d9/d8f/struct_s_r_datalog_1_1_map_clauses_to_column_sources" ],
      [ "GetVersionFromSources", "d9/dd4/struct_s_r_datalog_1_1_get_version_from_sources.html", null ],
      [ "GetVersionFromSources&lt; std::tuple&lt; mir::ColumnSource&lt; Index, BVars &gt; &gt; &gt;", "d9/de3/struct_s_r_datalog_1_1_get_version_from_sources_3_01std_1_1tuple_3_01mir_1_1_column_source_3_01_f60b00afddee32d6b7f763760be5360d.html", null ],
      [ "GetVersionFromSources&lt; std::tuple&lt; mir::ColumnSource&lt; Index, BVars &gt;, Rest... &gt; &gt;", "d1/de0/struct_s_r_datalog_1_1_get_version_from_sources_3_01std_1_1tuple_3_01mir_1_1_column_source_3_01_915f49f23649cd10ee9ca1caebc57e80.html", null ],
      [ "FoldState", "da/d07/struct_s_r_datalog_1_1_fold_state.html", "da/d07/struct_s_r_datalog_1_1_fold_state" ],
      [ "ProcessOneVariable_impl", "de/d58/struct_s_r_datalog_1_1_process_one_variable__impl.html", "de/d58/struct_s_r_datalog_1_1_process_one_variable__impl" ],
      [ "ProcessOneVariable", "d3/d24/struct_s_r_datalog_1_1_process_one_variable.html", "d3/d24/struct_s_r_datalog_1_1_process_one_variable" ],
      [ "CompileBodiesToMIR", "d5/dc9/struct_s_r_datalog_1_1_compile_bodies_to_m_i_r.html", "d5/dc9/struct_s_r_datalog_1_1_compile_bodies_to_m_i_r" ],
      [ "CompileHeadsToMIR", "d3/d1a/struct_s_r_datalog_1_1_compile_heads_to_m_i_r.html", "d3/d1a/struct_s_r_datalog_1_1_compile_heads_to_m_i_r" ],
      [ "CompileRuleToMIR", "d8/df6/struct_s_r_datalog_1_1_compile_rule_to_m_i_r.html", null ],
      [ "CompileRuleToMIR&lt; Rule&lt; Head, Body, JoinPlan &gt; &gt;", "d0/db0/struct_s_r_datalog_1_1_compile_rule_to_m_i_r_3_01_rule_3_01_head_00_01_body_00_01_join_plan_01_4_01_4.html", "d0/db0/struct_s_r_datalog_1_1_compile_rule_to_m_i_r_3_01_rule_3_01_head_00_01_body_00_01_join_plan_01_4_01_4" ],
      [ "GetHeadSchemas", "da/d42/struct_s_r_datalog_1_1_get_head_schemas.html", null ],
      [ "GetHeadSchemas&lt; Rule&lt; Head, Body, JoinPlan &gt; &gt;", "d0/d78/struct_s_r_datalog_1_1_get_head_schemas_3_01_rule_3_01_head_00_01_body_00_01_join_plan_01_4_01_4.html", "d0/d78/struct_s_r_datalog_1_1_get_head_schemas_3_01_rule_3_01_head_00_01_body_00_01_join_plan_01_4_01_4" ],
      [ "IndexSpec", "dd/da3/struct_s_r_datalog_1_1_index_spec.html", "dd/da3/struct_s_r_datalog_1_1_index_spec" ],
      [ "IndexSpecHash", "dc/d50/struct_s_r_datalog_1_1_index_spec_hash.html", "dc/d50/struct_s_r_datalog_1_1_index_spec_hash" ],
      [ "DictionaryCodec", "d2/d83/class_s_r_datalog_1_1_dictionary_codec.html", "d2/d83/class_s_r_datalog_1_1_dictionary_codec" ],
      [ "Prefix", "db/d9b/struct_s_r_datalog_1_1_prefix.html", "db/d9b/struct_s_r_datalog_1_1_prefix" ],
      [ "Relation", "d0/d94/class_s_r_datalog_1_1_relation.html", "d0/d94/class_s_r_datalog_1_1_relation" ],
      [ "is_node_handle", "d0/da3/struct_s_r_datalog_1_1is__node__handle.html", null ],
      [ "is_index", "da/d1f/struct_s_r_datalog_1_1is__index.html", null ],
      [ "GetIncrementalRelationsFromFixpoint", "d7/d63/struct_s_r_datalog_1_1_get_incremental_relations_from_fixpoint.html", null ],
      [ "GetIncrementalRelationsFromFixpoint&lt; AST::Fixpoint&lt; Rules... &gt; &gt;", "d4/d5a/struct_s_r_datalog_1_1_get_incremental_relations_from_fixpoint_3_01_a_s_t_1_1_fixpoint_3_01_rules_8_8_8_01_4_01_4.html", "d4/d5a/struct_s_r_datalog_1_1_get_incremental_relations_from_fixpoint_3_01_a_s_t_1_1_fixpoint_3_01_rules_8_8_8_01_4_01_4" ],
      [ "GetIncrementalRelationsFromRules", "d2/d77/struct_s_r_datalog_1_1_get_incremental_relations_from_rules.html", null ],
      [ "GetIncrementalRelationsFromRules&lt; std::tuple&lt; Rules... &gt; &gt;", "d5/d5b/struct_s_r_datalog_1_1_get_incremental_relations_from_rules_3_01std_1_1tuple_3_01_rules_8_8_8_01_4_01_4.html", "d5/d5b/struct_s_r_datalog_1_1_get_incremental_relations_from_rules_3_01std_1_1tuple_3_01_rules_8_8_8_01_4_01_4" ]
    ] ],
    [ "BooleanSR", "d8/dcb/struct_boolean_s_r.html", "d8/dcb/struct_boolean_s_r" ],
    [ "is_mpi_direct_mappable", "d4/d6e/structis__mpi__direct__mappable.html", null ],
    [ "is_mpi_direct_mappable&lt; bool &gt;", "d6/d7f/structis__mpi__direct__mappable_3_01bool_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; char &gt;", "dd/d29/structis__mpi__direct__mappable_3_01char_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; double &gt;", "d7/d3e/structis__mpi__direct__mappable_3_01double_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; float &gt;", "df/df8/structis__mpi__direct__mappable_3_01float_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; long double &gt;", "db/d81/structis__mpi__direct__mappable_3_01long_01double_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; std::int16_t &gt;", "dc/dde/structis__mpi__direct__mappable_3_01std_1_1int16__t_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; std::int32_t &gt;", "de/dbb/structis__mpi__direct__mappable_3_01std_1_1int32__t_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; std::int64_t &gt;", "d9/dff/structis__mpi__direct__mappable_3_01std_1_1int64__t_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; std::int8_t &gt;", "de/d1e/structis__mpi__direct__mappable_3_01std_1_1int8__t_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; std::uint16_t &gt;", "d0/ddf/structis__mpi__direct__mappable_3_01std_1_1uint16__t_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; std::uint32_t &gt;", "de/de5/structis__mpi__direct__mappable_3_01std_1_1uint32__t_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; std::uint64_t &gt;", "dd/d13/structis__mpi__direct__mappable_3_01std_1_1uint64__t_01_4.html", null ],
    [ "is_mpi_direct_mappable&lt; std::uint8_t &gt;", "d8/de1/structis__mpi__direct__mappable_3_01std_1_1uint8__t_01_4.html", null ],
    [ "NatSemiring", "df/df4/struct_nat_semiring.html", "df/df4/struct_nat_semiring" ],
    [ "NaturalBag", "dc/d1d/struct_natural_bag.html", "dc/d1d/struct_natural_bag" ],
    [ "Point", "d8/dc8/struct_point.html", "d8/dc8/struct_point" ],
    [ "ProbIndep", "d8/dd8/struct_prob_indep.html", "d8/dd8/struct_prob_indep" ],
    [ "Relation", "d3/dc1/class_relation.html", null ],
    [ "semiring_traits", "d7/dfd/structsemiring__traits.html", null ],
    [ "semiring_traits&lt; BooleanSR &gt;", "de/dab/structsemiring__traits_3_01_boolean_s_r_01_4.html", null ],
    [ "semiring_traits&lt; ProbIndep &gt;", "dc/d7e/structsemiring__traits_3_01_prob_indep_01_4.html", null ]
];