var hierarchy =
[
    [ "SRDatalog::AllIndicesFromProgram&lt; Program, RelationsTuple &gt;", "dd/d24/struct_s_r_datalog_1_1_all_indices_from_program.html", null ],
    [ "SRDatalog::AST::ArityMismatchError&lt; schema, ExpectedArity, ActualArity &gt;", "d1/d3d/struct_s_r_datalog_1_1_a_s_t_1_1_arity_mismatch_error.html", null ],
    [ "std::bool_constant", null, [
      [ "SRDatalog::is_index< T >", "da/d1f/struct_s_r_datalog_1_1is__index.html", null ]
    ] ],
    [ "BooleanSR", "d8/dcb/struct_boolean_s_r.html", null ],
    [ "SRDatalog::detail::BuildAllIndices_Impl&lt; IndexSpecList, AllRelationsTuple &gt;", "d9/d55/struct_s_r_datalog_1_1detail_1_1_build_all_indices___impl.html", null ],
    [ "SRDatalog::detail::BuildIndexHelper&lt; AllRelationsTuple &gt;", "dd/dfb/struct_s_r_datalog_1_1detail_1_1_build_index_helper.html", null ],
    [ "SRDatalog::AST::Clause&lt; schema, Ver, Vars &gt;", "d4/dbf/struct_s_r_datalog_1_1_a_s_t_1_1_clause.html", null ],
    [ "SRDatalog::ClauseToColumnSource_impl&lt; Clause, VarToBind, BoundVars, JoinPlan &gt;", "d5/d7b/struct_s_r_datalog_1_1_clause_to_column_source__impl.html", null ],
    [ "SRDatalog::Column&lt; T &gt;", "d3/d99/class_s_r_datalog_1_1_column.html", null ],
    [ "SRDatalog::AST::mir::ColumnJoin", "d3/d92/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1_column_join.html", null ],
    [ "SRDatalog::AST::mir::ColumnSource&lt; Index, BVars &gt;", "d4/dea/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1_column_source.html", null ],
    [ "SRDatalog::CompileBodiesToMIR&lt; BodyClauses, GlobalJoinPlan, Indices &gt;", "d5/dc9/struct_s_r_datalog_1_1_compile_bodies_to_m_i_r.html", null ],
    [ "SRDatalog::CompileHeadsToMIR&lt; HeadClauses &gt;", "d3/d1a/struct_s_r_datalog_1_1_compile_heads_to_m_i_r.html", null ],
    [ "SRDatalog::CompileRuleToMIR&lt; Rule &gt;", "d8/df6/struct_s_r_datalog_1_1_compile_rule_to_m_i_r.html", null ],
    [ "SRDatalog::CompileRuleToMIR&lt; Rule&lt; Head, Body, JoinPlan &gt; &gt;", "d0/db0/struct_s_r_datalog_1_1_compile_rule_to_m_i_r_3_01_rule_3_01_head_00_01_body_00_01_join_plan_01_4_01_4.html", null ],
    [ "SRDatalog::ComputeIndicesForRules&lt; RuleList &gt;", "df/d67/struct_s_r_datalog_1_1_compute_indices_for_rules.html", null ],
    [ "SRDatalog::ComputeNaiveIndices&lt; rule &gt;", "d3/dd6/struct_s_r_datalog_1_1_compute_naive_indices.html", null ],
    [ "SRDatalog::ComputeNaiveIndices&lt; Rule&lt; Head, Body, JoinPlan &gt; &gt;", "d0/dad/struct_s_r_datalog_1_1_compute_naive_indices_3_01_rule_3_01_head_00_01_body_00_01_join_plan_01_4_01_4.html", null ],
    [ "SRDatalog::AST::Const&lt; Func &gt;", "db/d28/struct_s_r_datalog_1_1_a_s_t_1_1_const.html", null ],
    [ "SRDatalog::AST::CppExpr&lt; CapturedVars, Func &gt;", "d6/d11/struct_s_r_datalog_1_1_a_s_t_1_1_cpp_expr.html", null ],
    [ "SRDatalog::AST::DatabaseToRelationTypes&lt; Database&lt; Schemas... &gt; &gt;", "d5/d73/struct_s_r_datalog_1_1_a_s_t_1_1_database_to_relation_types_3_01_database_3_01_schemas_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::AST::mir::DestinationRelation", "da/dd1/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1_destination_relation.html", null ],
    [ "SRDatalog::DictionaryCodec&lt; T &gt;", "d2/d83/class_s_r_datalog_1_1_dictionary_codec.html", null ],
    [ "std::false_type", null, [
      [ "SRDatalog::AST::is_cpp_expr< CppExpr< std::tuple< Vars... >, Func > >", "d4/de8/struct_s_r_datalog_1_1_a_s_t_1_1is__cpp__expr_3_01_cpp_expr_3_01std_1_1tuple_3_01_vars_8_8_8_01_4_00_01_func_01_4_01_4.html", null ],
      [ "SRDatalog::AST::is_database< Database< Schemas... > >", "db/db2/struct_s_r_datalog_1_1_a_s_t_1_1is__database_3_01_database_3_01_schemas_8_8_8_01_4_01_4.html", null ],
      [ "SRDatalog::AST::mir::is_bound_vars< BoundVars< Vars... > >", "dc/d61/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1is__bound__vars_3_01_bound_vars_3_01_vars_8_8_8_01_4_01_4.html", null ],
      [ "SRDatalog::detail::is_relation_ref< Relation< SR, Attrs... > & >", "d8/d08/struct_s_r_datalog_1_1detail_1_1is__relation__ref_3_01_relation_3_01_s_r_00_01_attrs_8_8_8_01_4_01_6_01_4.html", null ],
      [ "SRDatalog::is_let_clause_for_var_impl< Var, LetClause< Var, Expr > >", "d4/df1/struct_s_r_datalog_1_1is__let__clause__for__var__impl_3_01_var_00_01_let_clause_3_01_var_00_01_expr_01_4_01_4.html", null ],
      [ "is_mpi_direct_mappable< bool >", "d6/d7f/structis__mpi__direct__mappable_3_01bool_01_4.html", null ],
      [ "is_mpi_direct_mappable< char >", "dd/d29/structis__mpi__direct__mappable_3_01char_01_4.html", null ],
      [ "is_mpi_direct_mappable< double >", "d7/d3e/structis__mpi__direct__mappable_3_01double_01_4.html", null ],
      [ "is_mpi_direct_mappable< float >", "df/df8/structis__mpi__direct__mappable_3_01float_01_4.html", null ],
      [ "is_mpi_direct_mappable< long double >", "db/d81/structis__mpi__direct__mappable_3_01long_01double_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::int16_t >", "dc/dde/structis__mpi__direct__mappable_3_01std_1_1int16__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::int32_t >", "de/dbb/structis__mpi__direct__mappable_3_01std_1_1int32__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::int64_t >", "d9/dff/structis__mpi__direct__mappable_3_01std_1_1int64__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::int8_t >", "de/d1e/structis__mpi__direct__mappable_3_01std_1_1int8__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::uint16_t >", "d0/ddf/structis__mpi__direct__mappable_3_01std_1_1uint16__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::uint32_t >", "de/de5/structis__mpi__direct__mappable_3_01std_1_1uint32__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::uint64_t >", "dd/d13/structis__mpi__direct__mappable_3_01std_1_1uint64__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::uint8_t >", "d8/de1/structis__mpi__direct__mappable_3_01std_1_1uint8__t_01_4.html", null ],
      [ "SRDatalog::AST::is_cpp_expr< T >", "db/d4b/struct_s_r_datalog_1_1_a_s_t_1_1is__cpp__expr.html", null ],
      [ "SRDatalog::AST::is_database< T >", "d4/d8a/struct_s_r_datalog_1_1_a_s_t_1_1is__database.html", null ],
      [ "SRDatalog::AST::mir::is_bound_vars< T >", "dc/dde/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1is__bound__vars.html", null ],
      [ "SRDatalog::detail::is_relation_ref< T >", "df/d0f/struct_s_r_datalog_1_1detail_1_1is__relation__ref.html", null ],
      [ "SRDatalog::is_let_clause_for_var_impl< Var, Clause >", "d5/da4/struct_s_r_datalog_1_1is__let__clause__for__var__impl.html", null ],
      [ "SRDatalog::is_node_handle< T >", "d0/da3/struct_s_r_datalog_1_1is__node__handle.html", null ],
      [ "is_mpi_direct_mappable< T >", "d4/d6e/structis__mpi__direct__mappable.html", null ]
    ] ],
    [ "SRDatalog::FindLetClauses&lt; Var, BodyClauses &gt;", "d1/d9a/struct_s_r_datalog_1_1_find_let_clauses.html", null ],
    [ "SRDatalog::FindNormalClausesWithVar&lt; Var, BodyClauses &gt;", "de/d67/struct_s_r_datalog_1_1_find_normal_clauses_with_var.html", null ],
    [ "SRDatalog::AST::FindTermIndex&lt; T, TermList &gt;", "dc/db4/struct_s_r_datalog_1_1_a_s_t_1_1_find_term_index.html", null ],
    [ "SRDatalog::AST::FixpointToMp11List&lt; Fixpoint&lt; Rules... &gt; &gt;", "df/d00/struct_s_r_datalog_1_1_a_s_t_1_1_fixpoint_to_mp11_list_3_01_fixpoint_3_01_rules_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::FoldState&lt; BoundVars, AccumulatedOps &gt;", "da/d07/struct_s_r_datalog_1_1_fold_state.html", null ],
    [ "SRDatalog::detail::GenerateIterator&lt; Source, DB, StateMap &gt;", "d8/de1/struct_s_r_datalog_1_1detail_1_1_generate_iterator.html", null ],
    [ "SRDatalog::detail::GenerateIterator&lt; mir::ColumnSource&lt; IndexSpecT&lt; Schema, std::integer_sequence&lt; int, Cols... &gt;, Ver &gt;, PrefixVars &gt;, DB, StateMap &gt;", "d2/d4d/struct_s_r_datalog_1_1detail_1_1_generate_iterator_3_01mir_1_1_column_source_3_01_index_spec_t_31a7820df72adc7a13bc39cb3e44262da.html", null ],
    [ "SRDatalog::AST::GetAllRulesFromQueries&lt; QueryList &gt;", "d6/d4d/struct_s_r_datalog_1_1_a_s_t_1_1_get_all_rules_from_queries.html", null ],
    [ "SRDatalog::AST::GetClauseVars&lt; C &gt;", "da/dea/struct_s_r_datalog_1_1_a_s_t_1_1_get_clause_vars.html", null ],
    [ "SRDatalog::AST::GetClauseVars&lt; C &gt;", "dd/dc6/struct_s_r_datalog_1_1_a_s_t_1_1_get_clause_vars_3_01_c_01_4.html", null ],
    [ "SRDatalog::AST::GetExprDependencies&lt; Expr &gt;", "d5/dcd/struct_s_r_datalog_1_1_a_s_t_1_1_get_expr_dependencies.html", null ],
    [ "SRDatalog::AST::GetExprDependencies&lt; CppExpr&lt; CapturedVars, Func &gt; &gt;", "db/da6/struct_s_r_datalog_1_1_a_s_t_1_1_get_expr_dependencies_3_01_cpp_expr_3_01_captured_vars_00_01_func_01_4_01_4.html", null ],
    [ "SRDatalog::GetHeadSchemas&lt; Rule &gt;", "da/d42/struct_s_r_datalog_1_1_get_head_schemas.html", null ],
    [ "SRDatalog::GetHeadSchemas&lt; Rule&lt; Head, Body, JoinPlan &gt; &gt;", "d0/d78/struct_s_r_datalog_1_1_get_head_schemas_3_01_rule_3_01_head_00_01_body_00_01_join_plan_01_4_01_4.html", null ],
    [ "SRDatalog::GetIncrementalRelationsFromFixpoint&lt; FP &gt;", "d7/d63/struct_s_r_datalog_1_1_get_incremental_relations_from_fixpoint.html", null ],
    [ "SRDatalog::GetIncrementalRelationsFromFixpoint&lt; AST::Fixpoint&lt; Rules... &gt; &gt;", "d4/d5a/struct_s_r_datalog_1_1_get_incremental_relations_from_fixpoint_3_01_a_s_t_1_1_fixpoint_3_01_rules_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::GetIncrementalRelationsFromRules&lt; RuleList &gt;", "d2/d77/struct_s_r_datalog_1_1_get_incremental_relations_from_rules.html", null ],
    [ "SRDatalog::GetIncrementalRelationsFromRules&lt; std::tuple&lt; Rules... &gt; &gt;", "d5/d5b/struct_s_r_datalog_1_1_get_incremental_relations_from_rules_3_01std_1_1tuple_3_01_rules_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::GetIndexForClause&lt; Clause, GlobalJoinPlan &gt;", "d7/d48/struct_s_r_datalog_1_1_get_index_for_clause.html", null ],
    [ "SRDatalog::AST::GetLetClauseVars&lt; LC &gt;", "d4/d47/struct_s_r_datalog_1_1_a_s_t_1_1_get_let_clause_vars.html", null ],
    [ "SRDatalog::AST::GetLetClauseVars&lt; LetClause&lt; V, CppExpr&lt; CVars, F &gt; &gt; &gt;", "df/dbb/struct_s_r_datalog_1_1_a_s_t_1_1_get_let_clause_vars_3_01_let_clause_3_01_v_00_01_cpp_expr_3_01_c_vars_00_01_f_01_4_01_4_01_4.html", null ],
    [ "SRDatalog::AST::GetNormalClauseSchema&lt; C &gt;", "da/dae/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_schema.html", null ],
    [ "SRDatalog::AST::GetNormalClauseSchema&lt; Clause&lt; S, Ver, Vars... &gt; &gt;", "d0/d48/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_schema_3_01_clause_3_01_s_00_01_ver_00_01_vars_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::AST::GetNormalClauseTerms&lt; C &gt;", "d0/de5/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_terms.html", null ],
    [ "SRDatalog::AST::GetNormalClauseTerms&lt; Clause&lt; S, Ver, Vars... &gt; &gt;", "df/d69/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_terms_3_01_clause_3_01_s_00_01_ver_00_01_vars_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::AST::GetNormalClauseVersion&lt; C &gt;", "d0/d54/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_version.html", null ],
    [ "SRDatalog::AST::GetNormalClauseVersion&lt; Clause&lt; S, Ver, Vars... &gt; &gt;", "d8/d4b/struct_s_r_datalog_1_1_a_s_t_1_1_get_normal_clause_version_3_01_clause_3_01_s_00_01_ver_00_01_vars_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::detail::GetPayloadValues&lt; Terms, StateMap &gt;", "df/d8a/struct_s_r_datalog_1_1detail_1_1_get_payload_values.html", null ],
    [ "SRDatalog::detail::GetPayloadValues&lt; std::tuple&lt; Terms... &gt;, StateMap &gt;", "d5/d61/struct_s_r_datalog_1_1detail_1_1_get_payload_values_3_01std_1_1tuple_3_01_terms_8_8_8_01_4_00_01_state_map_01_4.html", null ],
    [ "SRDatalog::detail::GetPayloadValues&lt; std::tuple&lt;&gt;, StateMap &gt;", "df/ddd/struct_s_r_datalog_1_1detail_1_1_get_payload_values_3_01std_1_1tuple_3_4_00_01_state_map_01_4.html", null ],
    [ "SRDatalog::detail::GetPrefixValues&lt; PrefixVars, StateMap &gt;", "d3/d45/struct_s_r_datalog_1_1detail_1_1_get_prefix_values.html", null ],
    [ "SRDatalog::detail::GetPrefixValues&lt; mir::BoundVars&lt; Vars... &gt;, StateMap &gt;", "da/df8/struct_s_r_datalog_1_1detail_1_1_get_prefix_values_3_01mir_1_1_bound_vars_3_01_vars_8_8_8_01_4_00_01_state_map_01_4.html", null ],
    [ "SRDatalog::AST::GetRulesFromFixpoint&lt; FP &gt;", "d6/d31/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_fixpoint.html", null ],
    [ "SRDatalog::AST::GetRulesFromFixpoint&lt; Fixpoint&lt; Rules... &gt; &gt;", "d7/df4/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_fixpoint_3_01_fixpoint_3_01_rules_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::AST::GetRulesFromNonIterativeRuleSets&lt; NonIterativeRuleSets&lt; Rules... &gt; &gt;", "d4/db4/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_non_iterative_rule_sets_3_01_non_iterative_rule_sets_3_01_rules_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::AST::GetRulesFromQuery&lt; Q &gt;", "d9/d56/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_query.html", null ],
    [ "SRDatalog::AST::GetRulesFromQuery&lt; Fixpoint&lt; Rules... &gt; &gt;", "d4/d7b/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_query_3_01_fixpoint_3_01_rules_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::AST::GetRulesFromQuery&lt; NonIterativeRuleSets&lt; Rules... &gt; &gt;", "df/da3/struct_s_r_datalog_1_1_a_s_t_1_1_get_rules_from_query_3_01_non_iterative_rule_sets_3_01_rules_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::detail::GetValueFromState&lt; VarToFind, StateMap &gt;", "d0/d27/struct_s_r_datalog_1_1detail_1_1_get_value_from_state.html", null ],
    [ "SRDatalog::AST::GetVarsFromTerm&lt; T &gt;", "d3/deb/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term.html", null ],
    [ "SRDatalog::AST::GetVarsFromTerm&lt; C &gt;", "df/d9f/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term_3_01_c_01_4.html", null ],
    [ "SRDatalog::AST::GetVarsFromTerm&lt; CppExpr&lt; CVars, F &gt; &gt;", "d2/d87/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term_3_01_cpp_expr_3_01_c_vars_00_01_f_01_4_01_4.html", null ],
    [ "SRDatalog::AST::GetVarsFromTerm&lt; V &gt;", "d0/d5e/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_term_3_01_v_01_4.html", null ],
    [ "SRDatalog::AST::GetVarsFromTerms&lt; Terms &gt;", "dd/d28/struct_s_r_datalog_1_1_a_s_t_1_1_get_vars_from_terms.html", null ],
    [ "SRDatalog::GetVersionFromSources&lt; Sources &gt;", "d9/dd4/struct_s_r_datalog_1_1_get_version_from_sources.html", null ],
    [ "SRDatalog::GetVersionFromSources&lt; std::tuple&lt; mir::ColumnSource&lt; Index, BVars &gt; &gt; &gt;", "d9/de3/struct_s_r_datalog_1_1_get_version_from_sources_3_01std_1_1tuple_3_01mir_1_1_column_source_3_01_f60b00afddee32d6b7f763760be5360d.html", null ],
    [ "SRDatalog::GetVersionFromSources&lt; std::tuple&lt; mir::ColumnSource&lt; Index, BVars &gt;, Rest... &gt; &gt;", "d1/de0/struct_s_r_datalog_1_1_get_version_from_sources_3_01std_1_1tuple_3_01mir_1_1_column_source_3_01_915f49f23649cd10ee9ca1caebc57e80.html", null ],
    [ "SRDatalog::Relation&lt; SR, AttrTs &gt;::HashTrieIndex", "df/d5a/class_s_r_datalog_1_1_relation_1_1_hash_trie_index.html", null ],
    [ "SRDatalog::Relation&lt; SR, AttrTs &gt;::HashTrieIndex::Impl", "d3/dbf/struct_s_r_datalog_1_1_relation_1_1_hash_trie_index_1_1_impl.html", null ],
    [ "SRDatalog::detail::IndexRelInDBRels&lt; T, Tuple &gt;", "dd/d2a/struct_s_r_datalog_1_1detail_1_1_index_rel_in_d_b_rels.html", null ],
    [ "SRDatalog::IndexSpec", "dd/da3/struct_s_r_datalog_1_1_index_spec.html", null ],
    [ "SRDatalog::IndexSpecHash", "dc/d50/struct_s_r_datalog_1_1_index_spec_hash.html", null ],
    [ "SRDatalog::AST::IndexSpecT&lt; schema, ColumnIndexes, Ver &gt;", "d3/d0c/struct_s_r_datalog_1_1_a_s_t_1_1_index_spec_t.html", null ],
    [ "SRDatalog::AST::InitDatabaseHelper&lt; DB &gt;", "d8/dfd/struct_s_r_datalog_1_1_a_s_t_1_1_init_database_helper.html", null ],
    [ "SRDatalog::AST::InitDatabaseHelper&lt; Database&lt; Schemas... &gt; &gt;", "d8/dd2/struct_s_r_datalog_1_1_a_s_t_1_1_init_database_helper_3_01_database_3_01_schemas_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::AST::JoinPlan&lt; Vars &gt;", "d4/d58/struct_s_r_datalog_1_1_a_s_t_1_1_join_plan.html", null ],
    [ "SRDatalog::AST::LetClause", "d9/d11/struct_s_r_datalog_1_1_a_s_t_1_1_let_clause.html", null ],
    [ "SRDatalog::MapClausesToColumnSources&lt; VarToBind, NormalClauses, BoundVars, JoinPlan &gt;", "d9/d8f/struct_s_r_datalog_1_1_map_clauses_to_column_sources.html", null ],
    [ "SRDatalog::MapClausesToSpecs_Impl&lt; BodyClauses, GlobalJoinPlan &gt;", "d0/d7f/struct_s_r_datalog_1_1_map_clauses_to_specs___impl.html", null ],
    [ "SRDatalog::AST::MapVarsToColumnIndexes&lt; ClauseTerms, VarAccessOrder &gt;", "d1/d47/struct_s_r_datalog_1_1_a_s_t_1_1_map_vars_to_column_indexes.html", null ],
    [ "SRDatalog::detail::MIRExecutor&lt; MIRPlan, StateMap &gt;", "dc/d68/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor.html", null ],
    [ "SRDatalog::detail::MIRExecutor&lt; std::tuple&lt; HeadOp, TailOps... &gt;, StateMap &gt;", "dd/d3e/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor_3_01std_1_1tuple_3_01_head_op_00_01_tail_ops_8_8_8_01_4_00_01_state_map_01_4.html", null ],
    [ "SRDatalog::detail::MIRExecutor&lt; std::tuple&lt; LetClause&lt; VarToBind, CppExpr&lt; CapturedVars, Func &gt; &gt;, TailOps... &gt;, StateMap &gt;", "d1/d9e/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor_3_01std_1_1tuple_3_01_let_clause_3_01_var_to_bin8907e8d68030a7c70648f497f908557e.html", null ],
    [ "SRDatalog::detail::MIRExecutor&lt; std::tuple&lt; mir::ColumnJoin&lt; VarToBind, Sources &gt;, TailOps... &gt;, StateMap &gt;", "d4/d88/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor_3_01std_1_1tuple_3_01mir_1_1_column_join_3_01_vaccde6c0ac674a2e9c46fbf1bf30fc0ee.html", null ],
    [ "SRDatalog::detail::MIRExecutor&lt; std::tuple&lt; mir::DestinationRelation&lt; Schema, Terms, Ver &gt;, TailOps... &gt;, StateMap &gt;", "d9/d4e/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor_3_01std_1_1tuple_3_01mir_1_1_destination_relatiod77068713e8e97a230041d4e4f85930c.html", null ],
    [ "SRDatalog::detail::MIRExecutor&lt; std::tuple&lt;&gt;, StateMap &gt;", "d4/dab/struct_s_r_datalog_1_1detail_1_1_m_i_r_executor_3_01std_1_1tuple_3_4_00_01_state_map_01_4.html", null ],
    [ "NatSemiring", "df/df4/struct_nat_semiring.html", null ],
    [ "NaturalBag", "dc/d1d/struct_natural_bag.html", null ],
    [ "SRDatalog::Relation&lt; SR, AttrTs &gt;::HashTrieIndex::Impl::Node", "d3/d20/struct_s_r_datalog_1_1_relation_1_1_hash_trie_index_1_1_impl_1_1_node.html", null ],
    [ "SRDatalog::Relation&lt; SR, AttrTs &gt;::HashTrieIndex::NodeHandle", "d4/ddd/class_s_r_datalog_1_1_relation_1_1_hash_trie_index_1_1_node_handle.html", null ],
    [ "SRDatalog::AST::NonIterativeRuleSets&lt; Rules &gt;", "dd/dbc/struct_s_r_datalog_1_1_a_s_t_1_1_non_iterative_rule_sets.html", null ],
    [ "Point", "d8/dc8/struct_point.html", null ],
    [ "SRDatalog::Prefix&lt; Ts &gt;", "db/d9b/struct_s_r_datalog_1_1_prefix.html", null ],
    [ "ProbIndep", "d8/dd8/struct_prob_indep.html", null ],
    [ "SRDatalog::ProcessOneVariable&lt; AllJoinPlan, AllBodyClauses, Indices &gt;", "d3/d24/struct_s_r_datalog_1_1_process_one_variable.html", null ],
    [ "SRDatalog::ProcessOneVariable_impl&lt; State, VarToBind, AllJoinPlan, AllBodyClauses, Indices &gt;", "de/d58/struct_s_r_datalog_1_1_process_one_variable__impl.html", null ],
    [ "SRDatalog::AST::Program&lt; db, QueryList &gt;", "de/dd6/struct_s_r_datalog_1_1_a_s_t_1_1_program.html", null ],
    [ "Relation&lt; SR, AttrTs &gt;", "d3/dc1/class_relation.html", null ],
    [ "SRDatalog::Relation&lt; SR, AttrTs &gt;", "d0/d94/class_s_r_datalog_1_1_relation.html", null ],
    [ "SRDatalog::AST::RelationSchema&lt; Name, SR, AttrTs &gt;", "d0/d70/struct_s_r_datalog_1_1_a_s_t_1_1_relation_schema.html", null ],
    [ "SRDatalog::AST::SemiNaiveDatabase&lt; DBType &gt;", "d2/d05/struct_s_r_datalog_1_1_a_s_t_1_1_semi_naive_database.html", null ],
    [ "semiring_traits&lt; SR &gt;", "d7/dfd/structsemiring__traits.html", null ],
    [ "semiring_traits&lt; BooleanSR &gt;", "de/dab/structsemiring__traits_3_01_boolean_s_r_01_4.html", null ],
    [ "semiring_traits&lt; ProbIndep &gt;", "dc/d7e/structsemiring__traits_3_01_prob_indep_01_4.html", null ],
    [ "SRDatalog::to_fn&lt; Container &gt;", "d1/d8b/struct_s_r_datalog_1_1to__fn.html", null ],
    [ "SRDatalog::to_impl&lt; Container &gt;", "dc/d97/struct_s_r_datalog_1_1to__impl.html", null ],
    [ "std::true_type", null, [
      [ "SRDatalog::AST::is_cpp_expr< CppExpr< std::tuple< Vars... >, Func > >", "d4/de8/struct_s_r_datalog_1_1_a_s_t_1_1is__cpp__expr_3_01_cpp_expr_3_01std_1_1tuple_3_01_vars_8_8_8_01_4_00_01_func_01_4_01_4.html", null ],
      [ "SRDatalog::AST::is_database< Database< Schemas... > >", "db/db2/struct_s_r_datalog_1_1_a_s_t_1_1is__database_3_01_database_3_01_schemas_8_8_8_01_4_01_4.html", null ],
      [ "SRDatalog::AST::mir::is_bound_vars< BoundVars< Vars... > >", "dc/d61/struct_s_r_datalog_1_1_a_s_t_1_1mir_1_1is__bound__vars_3_01_bound_vars_3_01_vars_8_8_8_01_4_01_4.html", null ],
      [ "SRDatalog::detail::is_relation_ref< Relation< SR, Attrs... > & >", "d8/d08/struct_s_r_datalog_1_1detail_1_1is__relation__ref_3_01_relation_3_01_s_r_00_01_attrs_8_8_8_01_4_01_6_01_4.html", null ],
      [ "SRDatalog::is_let_clause_for_var_impl< Var, LetClause< Var, Expr > >", "d4/df1/struct_s_r_datalog_1_1is__let__clause__for__var__impl_3_01_var_00_01_let_clause_3_01_var_00_01_expr_01_4_01_4.html", null ],
      [ "is_mpi_direct_mappable< bool >", "d6/d7f/structis__mpi__direct__mappable_3_01bool_01_4.html", null ],
      [ "is_mpi_direct_mappable< char >", "dd/d29/structis__mpi__direct__mappable_3_01char_01_4.html", null ],
      [ "is_mpi_direct_mappable< double >", "d7/d3e/structis__mpi__direct__mappable_3_01double_01_4.html", null ],
      [ "is_mpi_direct_mappable< float >", "df/df8/structis__mpi__direct__mappable_3_01float_01_4.html", null ],
      [ "is_mpi_direct_mappable< long double >", "db/d81/structis__mpi__direct__mappable_3_01long_01double_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::int16_t >", "dc/dde/structis__mpi__direct__mappable_3_01std_1_1int16__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::int32_t >", "de/dbb/structis__mpi__direct__mappable_3_01std_1_1int32__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::int64_t >", "d9/dff/structis__mpi__direct__mappable_3_01std_1_1int64__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::int8_t >", "de/d1e/structis__mpi__direct__mappable_3_01std_1_1int8__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::uint16_t >", "d0/ddf/structis__mpi__direct__mappable_3_01std_1_1uint16__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::uint32_t >", "de/de5/structis__mpi__direct__mappable_3_01std_1_1uint32__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::uint64_t >", "dd/d13/structis__mpi__direct__mappable_3_01std_1_1uint64__t_01_4.html", null ],
      [ "is_mpi_direct_mappable< std::uint8_t >", "d8/de1/structis__mpi__direct__mappable_3_01std_1_1uint8__t_01_4.html", null ]
    ] ],
    [ "SRDatalog::AST::TStringToStringImpl&lt; TString&lt; chars... &gt; &gt;", "d3/d27/struct_s_r_datalog_1_1_a_s_t_1_1_t_string_to_string_impl_3_01_t_string_3_01chars_8_8_8_01_4_01_4.html", null ],
    [ "SRDatalog::AST::Var&lt; Name &gt;", "dc/dd9/struct_s_r_datalog_1_1_a_s_t_1_1_var.html", null ]
];